apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-management
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 15672
          name: http
        - containerPort: 5672
          name: amqp        

---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  type: LoadBalancer
  selector:
    app: rabbit
  ports:
  - port: 15672
    targetPort: 15672
    name: http
  - port: 5672
    targetPort: 5672
    name: amqp
